apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
spec:
  selector: {{include "common.api" . | nindent 4}}
  ports:
    - port: {{ .Values.api.port }}
      protocol: {{ .Values.api.protocol }}
      targetPort: {{ .Values.api.port }}
