apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.name }}
spec:
  selector: {{include "common.client" . | nindent 4}}
  ports:
    - port: {{ .Values.client.port }}
      protocol: {{ .Values.client.protocol }}
      targetPort: {{ .Values.client.port }}
  type: {{ .Values.client.type }} 
