apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.name }}
spec:
  selector:
    matchLabels: {{ include "common.client" . | nindent 6}}
  replicas: {{ .Values.client.replicas }}
  template:
    metadata:
      labels: {{ include "common.client" . | nindent 8}}
    spec:
      containers:
        - name: {{ .Values.client.name }}
          image: {{ .Values.client.image }}
          imagePullPolicy: {{ .Values.client.policy }}
          ports:
            - containerPort: {{ .Values.client.port }}
